layer: linear
param_path: ./data/feat.stn.fc3
data_dir: ./data
data_num: 10
regenerate: false

linear:
  in_features: 256
  out_features: 9

batchnorm1d:
  in_channels: 512

conv1d:
  in_channels: 3
  out_channels: 64