# if change targe/name, please check the `mode`!
target: layer  # op, layer, model
name: batchnorm1d
is_training: false

param_path: /home/tsyhahaha/default/feat.stn.bn5
data_dir: /home/tsyhahaha/CUDA-NN/data/
data_num: 10

mode: regenerate # test, regenerate, beat

linear:
  in_features: 1024
  out_features: 512

batchnorm1d:
  in_channels: 256

conv1d:
  in_channels:  128
  out_channels: 1024

pointnet:
  argmax: true
